name: 'Upload file'
description: 'Pixee action upload file'
author: 'Pixee'
inputs:
  file:
    description: 'File'
    required: true
  url:
    description: 'Pixee endpoint'
    required: true
outputs:
  start-at:
    description: 'Start at'
  status:
    description: 'Status'
runs:
  using: 'node20'
  main: './lib/upload-pixee-action.js'
