name: Share Static Analysis with Pixeebot
description: Upload file to Pixee
author: Pixee
inputs:
  file:
    description: File to be uploaded.
    required: true
  tool:
    description: >
      Specific property that identifies the tool related to the uploaded file.
      Allowed values: 'sonar', 'codeql', 'semgrep'
    required: true
  sonar-token:
    description: Sonar token
    required: false
  sonar-component-key:
    description: Sonar component key
    required: true
  sonar-api:
    description: Sonar API
    default: https://sonarcloud.io/api

outputs:
  status:
    description: |
      Status of the action execution.
      Possible values:
      - 'error': Indicates that the action encountered an error.
      - 'success': Indicates that the action completed successfully.

runs:
  using: node20
  main: ../dist/upload-file/index.js
