name: 'Upload file'
description: 'Upload file to Pixee'
author: 'Pixee'
inputs:
  url:
    description: 'Endpoint URL where the file will be uploaded.'
    required: false
  file:
    description: 'File to be uploaded.'
    required: true
  tool:
    description: >
      Specific property identifying the tool or service related to the uploaded file.
      Allowed values: 'sonar', 'codeql', 'semgrep'
    required: true
outputs:
  start-at:
    description: 'Start at'
  status:
    description: 'Status'
runs:
  using: 'node20'
  main: '../lib/upload-pixee-action.js'
